import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Project App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Proyecto de Estructura de Datos
        </h1>
        <li>Jonathan Adamson 8-875-373</li>
        <li>Alvan Samudio 4-807-1931</li>
        <li>Juan Taylor 8-971-255</li>
        <li>Jeremy Chacon 20-70-4741</li>

        <p className={styles.description}>
          Elija una estructura de Datos
        </p>

        <div className={styles.card}>
          <Link href="/pilas">
            <h2>Pilas &rarr;</h2>
          </Link>
        </div>
        <div className={styles.card}>
          <Link href="/colas">
            <h2>Colas &rarr;</h2>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by UTP
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
